services:
  n8n:
    container_name: n8n
    image: docker.n8n.io/n8nio/n8n
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
    environment:
      - GENERIC_TIMEZONE=Asia/Ho_Chi_Minh
    restart: unless-stopped
    networks:
      - microservices-net
networks:
  microservices-net:
    external: true
volumes:
  n8n_data:
